### PR TITLE
Initial Basic UI Test

### PR DESCRIPTION
**Pull request by davidhsonic**

### CODE REVIEW

**Comment by jlmayfield** [comment]
@monmouth-college-cs/monmouth-college-comp-335 The plan is for everyone to submit a review to this PR. We'll do an in-person review and merge on Monday.

**Review by jlmayfield — APPROVED** [review]
Needs to be tested on a device but otherwise good.

**Review by Shayno527 — APPROVED** [review]
Nice Job!

**Comment by AbhiJohal** [comment]
Looks good to me

**Review by AbhiJohal — APPROVED** [review]

**Review by Awallace8074 — APPROVED** [review]
### **_good job_**

**Review by phein — APPROVED** [review]

**Pull request merged**
